language: python
notifications:
  email:
    - jesse@codeforamerica.org
python:
  - "2.7"
before_install:
  - git submodule update --init --recursive
# command to install dependencies
install: pip install -r requirements.txt --use-mirrors
# command to run tests
script: coverage run tests.py; coverage report -m --omit socrata_python/Socrata.py
